#!/usr/bin/env bash
#
# Every icon the app ships, cut from design/knock_logo.svg.
#
#   ./scripts/icons.sh
#
# Needs Google Chrome (headless, to render the SVG) and ImageMagick 7
# (`brew install imagemagick`). Writes only into public/ and design/.
#
# ## Why a script and not eight commands in a comment
#
# The set has to stay in step. An icon updated in six places out of eight is
# worse than one nobody touched, because the ones left behind are the ones
# nobody is looking at - a favicon, a home-screen tile - and they go stale
# silently. One command, one source, all eight.
#
# ## The proportions are the old set's, measured off it
#
# Each icon is the mark at some fraction of a square canvas, and the fractions
# below were taken from the icons this replaces rather than invented. They
# encode real constraints, and the reasons are on each line.
#
# ## What is deliberately not transparent
#
# apple-touch-icon and the maskable icon carry an opaque ground. iOS has never
# supported transparency in a home-screen icon - it composites onto black - and
# Android crops a maskable icon to whatever shape the launcher likes, so a
# transparent one arrives with the corners of somebody else's mask showing
# through. The rest stay transparent: a favicon sits on a browser's own tab
# strip, which is a different colour in every theme.

set -euo pipefail
cd "$(dirname "$0")/.."

CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
[ -x "$CHROME" ] || { echo "Chrome not found at $CHROME" >&2; exit 1; }
command -v magick >/dev/null || { echo "ImageMagick 7 (magick) not found" >&2; exit 1; }

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# The master, far larger than anything cut from it - see design/mark.html for
# why that size in particular.
"$CHROME" --headless --disable-gpu --hide-scrollbars \
  --force-device-scale-factor=1 --window-size=2048,1976 \
  --virtual-time-budget=6000 --default-background-color=00000000 \
  --screenshot="$work/master.png" design/mark.html >/dev/null 2>&1

# Chrome lays the SVG out at 2042 of the 2048 it was given, so trim to the art
# itself: every size below is a fraction of the mark, and a stray column of
# nothing on one side would put all of them a pixel off centre.
magick "$work/master.png" -trim +repage "$work/mark.png"

# One icon: the mark at `percent` of a `size` square, over `ground`.
# Lanczos because these are big reductions and the default filter softens the
# white ring into the blue behind it.
cut() {
  local out=$1 size=$2 percent=$3 ground=$4
  local art=$(( size * percent / 100 ))
  magick "$work/mark.png" -filter Lanczos -resize "${art}x${art}" \
    -background "$ground" -gravity center -extent "${size}x${size}" \
    -strip -define png:compression-level=9 "$out"
}

# Transparent, and near enough full-bleed: a favicon is small enough already
# without spending a tenth of it on margin.
cut public/icon-512.png   512 92 none
cut public/icon-192.png   192 92 none
cut public/favicon-32.png  32 92 none

# Android crops this to whatever shape the launcher wants - circle, squircle,
# teardrop - so the mark keeps well inside the 80%-diameter safe circle.
cut public/icon-maskable.png 512 62 white

# iOS rounds the corners itself and crops nothing, so this needs less room than
# the maskable one. Opaque: see above.
cut public/apple-touch-icon.png 180 83 white

# 16 and 32 are the tab strip; 48 is what Windows and some bookmark lists ask
# for. Built from the 48 rather than each from the master, so the three agree.
cut "$work/ico.png" 48 92 none
magick "$work/ico.png" -define icon:auto-resize=48,32,16 public/favicon.ico

# The in-app mark, at its own proportions rather than boxed into a square -
# components/brand-mark.tsx declares this exact size, so the two move together.
magick "$work/mark.png" -filter Lanczos -resize 512x \
  -strip -define png:compression-level=9 public/knock-mark.png

# Nimiq Pay probes /icon.svg directly and draws it behind a round mask, so the
# mark stops well short of the canvas. The corner of a 227x219 mark sits
# 1.366 times its half-width from the centre, so anything past 73% of the
# canvas leaves that circle; 70% is that with a margin, and matches what the
# icon this replaces had measured.
#
# An SVG wrapping a PNG rather than the logo's own vector: knock_logo.svg is
# 950 kB, most of it one embedded raster, and it renders the seam described in
# design/mark.html. A flat 192px picture is smaller, sharper and has no
# filters to disagree about.
cut "$work/icon-svg.png" 192 70 none
{
  printf '%s\n' \
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 192 192" width="192" height="192">' \
    '  <title>Knock</title>' \
    '  <!-- Generated by scripts/icons.sh from design/knock_logo.svg. Do not edit:' \
    '       the next run overwrites it. Why a raster, and why 70%, are explained there. -->'
  printf '  <image href="data:image/png;base64,'
  base64 < "$work/icon-svg.png" | tr -d '\n'
  printf '"\n         width="192" height="192"/>\n</svg>\n'
} > public/icon.svg

# And the share card's mark, which is the same render at a different size.
magick "$work/mark.png" -filter Lanczos -resize 400x \
  -strip -define png:compression-level=9 design/og-mark.png

printf '%-30s %s\n' \
  public/icon-512.png        "$(stat -f%z public/icon-512.png) bytes" \
  public/icon-192.png        "$(stat -f%z public/icon-192.png) bytes" \
  public/favicon-32.png      "$(stat -f%z public/favicon-32.png) bytes" \
  public/favicon.ico         "$(stat -f%z public/favicon.ico) bytes" \
  public/icon-maskable.png   "$(stat -f%z public/icon-maskable.png) bytes" \
  public/apple-touch-icon.png "$(stat -f%z public/apple-touch-icon.png) bytes" \
  public/icon.svg            "$(stat -f%z public/icon.svg) bytes" \
  public/knock-mark.png      "$(stat -f%z public/knock-mark.png) bytes" \
  design/og-mark.png         "$(stat -f%z design/og-mark.png) bytes"
